Repository BCDA-APS/bluesky_training, pull requests merged in 2023-08, with the labels that each got.

#214 add installation checklist
  docs/source/instrument/_install_new_instrument.rst
Labels: documentation

#222 Diagnose and repair CI
  .github/workflows/unit-tests-pytest.yml
Labels: task

#218 141 git instructions
  .gitignore
  docs/source/_static/new-repo.png
  docs/source/_static/organization.png
  docs/source/_static/repo-created.png
  docs/source/instrument/_install_new_instrument.rst
  docs/source/reference/_git-help.rst
  docs/source/reference/_github_create_repo.md
Labels: documentation

#210 create environment for APS "cycle" 2023-3
  .gitignore
  CHANGES.rst
  bluesky/blueskyStarter.sh
  bluesky/environments/README.md
  bluesky/environments/archive/environment_2021_1.yml
  bluesky/environments/archive/environment_2021_2.yml
  bluesky/environments/archive/environment_2022_1.yml
  bluesky/environments/archive/environment_2022_2.yml
  bluesky/environments/archive/environment_2022_3.yml
  bluesky/environments/archive/environment_2023_1.yml
  bluesky/environments/environment_2023_3.yml
  docs/source/example/_specwriter.ipynb
  docs/source/howto/_custom_heater_positioner.ipynb
  docs/source/howto/_custom_plan.ipynb
  docs/source/howto/_images_darks_flats.ipynb
  docs/source/howto/getting_started.md
  docs/source/instrument/_configure_databroker.md
  docs/source/instrument/_install_new_instrument.rst
  docs/source/instrument/_test_new_instrument.md
  docs/source/reference/_create_conda_env.rst
Labels: task

#232 Not yet for haven-spc package
  CHANGES.rst
  bluesky/environments/environment_2023_3.yml
Labels: bug

#234 add sphinx_tabs.tabs extension last
  docs/source/conf.py
Labels: bug, documentation

#228 Use RUN_ENGINE_SCAN_ID_PV if defined
  bluesky/instrument/framework/initialize.py
  bluesky/instrument/framework/metadata.py
  bluesky/instrument/iconfig.yml
  bluesky/tests/test_scan_id_pv.py
Labels: enhancement

#235 add iconfig as routine diagnostic metadata
  bluesky/instrument/framework/metadata.py
Labels: enhancement

#236 add version string
  bluesky/instrument/iconfig.yml
Labels: enhancement

#238 use "zlib" as default HDF5 compression
  CHANGES.rst
  bluesky/instrument/devices/area_detector.py
Labels: enhancement

#239 new_bluesky_instrument uses latest release
  CHANGES.rst
  docs/source/changes.rst
  docs/source/index.rst
  new_bluesky_instrument.py
Labels: enhancement

#243 add NXWriter callback
  .gitignore
  bluesky/instrument/callbacks/__init__.py
  bluesky/instrument/callbacks/nexus_data_file_writer.py
  bluesky/instrument/iconfig.yml
  bluesky/instrument/session_logs.py
Labels: enhancement
