Repository BCDA-APS/bluesky_training, pull requests merged in 2023-05, with the labels that each got.

#143 Installation guide review
  README.md
  bluesky/environments/README.md
  bluesky/environments/environment_2023_2.yml
  docs/requirements.txt
  docs/source/_static/bluesky-in-lab.png
  docs/source/conf.py
  docs/source/howto/bluesky_cheat_sheet.md
  docs/source/howto/getting_started.md
  docs/source/howto/index.rst
  docs/source/index.rst
  docs/source/instrument/_directory_layout.rst
  docs/source/instrument/_install_new_instrument.md
  docs/source/instrument/_install_new_instrument.rst
  docs/source/instrument/_testing.md
  docs/source/instrument/describe_instrument.ipynb
  docs/source/instrument/index.rst
  docs/source/instrument/instrument_template.md
  docs/source/reference/_FAQ.rst
  docs/source/reference/_aps_data_management.md
  docs/source/reference/_conda_base.md
  docs/source/reference/_conda_environment.md
  docs/source/reference/_create_conda_env.md
  docs/source/reference/_ipython.rst
  docs/source/tutor/_command_review.ipynb
  docs/source/tutor/_start_bluesky_session.md
  docs/source/tutor/hello_world.ipynb
  docs/source/tutor/index.rst
Labels: documentation

#161 Repair CI workflows
  .github/workflows/pages.yml
  .github/workflows/unit-tests-pytest.yml
  docs/source/conf.py
Labels: bug

#157 rename one of the scripts used to start the queueserver
  bluesky/_run_qs.sh
  bluesky/qserver.sh
Labels: task

#164 BUG: could not import pvaccess in new environment
  bluesky/environments/environment_2023_2.yml
Labels: bug

#166 replace the URL
  docs/source/instrument/guide.md
Labels: documentation

#165 changes in blueskyStarter.sh
  bluesky/blueskyStarter.sh
  docs/source/instrument/_install_new_instrument.rst
  docs/source/tutor/hello_world.ipynb
  install.md
  new_bluesky_instrument.py
Labels: task

#162 add another symbol to iconfig
  bluesky/instrument/iconfig.yml
Labels: task

#177 wrap scan_id_epics with try..except
  bluesky/instrument/framework/metadata.py
Labels: task

#178 also set permissions on new bluesky directory
  new_bluesky_instrument.py
Labels: bug

#168 remove legacy /install.md document
  README.md
  docs/source/index.rst
  docs/source/instrument/describe_instrument.ipynb
  docs/source/tutor/_basic_a.ipynb
  docs/source/tutor/_basic_b.ipynb
  docs/source/tutor/_basic_c.ipynb
  install.md
Labels: documentation

#148 DOC clarify and generalize instruction to make XY plots from databroker.
  docs/source/howto/_plot_x_y_databroker.ipynb
Labels: documentation

#159 create unit tests for newSpecFile
  bluesky/instrument/callbacks/spec_data_file_writer.py
  bluesky/tests/20230509-191819.spec_data
  bluesky/tests/test_newSpecFile.py
Labels: bug

#185 restrict QS startup to one specific host
  bluesky/_run_qs.sh
Labels: task
