Repository BCDA-APS/bluesky_training, pull requests merged in 2023-06, with the labels that each got.

#187 remove redundant content from README in favor of docs
  README.md
  docs/source/index.rst
Labels: documentation, good first issue

#133 Examples of custom ophyd devices
  docs/source/_static/neat_stage_2apd.png
  docs/source/howto/_bluesky_queueserver.md
  docs/source/howto/_custom_heater_positioner.ipynb
  docs/source/howto/index.rst
  docs/source/reference/_FAQ.rst
  docs/source/tutor/_custom_device.rst
  docs/source/tutor/index.rst
Labels: documentation

#193 replace the Miniconda installer script example
  docs/source/reference/_conda_base.md
Labels: documentation

#188 convert URLs: nsls-ii.github.io -> blueskyproject.io
  .wip/flyers/flyer_template.ipynb
  docs/source/howto/_count_scaler.ipynb
  docs/source/howto/_synapps_sscan_1d_flyer.ipynb
  docs/source/tutor/_basic_a.ipynb
  docs/source/tutor/_basic_c.ipynb
  docs/source/tutor/_lesson1.ipynb
  docs/source/tutor/_lesson2.ipynb
  docs/source/tutor/_lesson3a.ipynb
Labels: documentation, good first issue

#186 Recognize that "beamline" is a single word
  .wip/lessons/diffractometer-4circle.ipynb
  docs/source/howto/_basic_aps_info.ipynb
  docs/source/howto/_bluesky_queueserver.md
  docs/source/howto/_synapps_sscan_1d_flyer.ipynb
  docs/source/howto/getting_started.md
  docs/source/index.rst
  docs/source/instrument/_test_bluesky_at_aps.md
  docs/source/instrument/describe_instrument.ipynb
  docs/source/reference/_git-help.rst
  docs/source/tutor/_lesson5a.ipynb
  docs/source/tutor/_lesson7.ipynb
Labels: documentation, good first issue, task

#194 keep a history of changes between versions
  CHANGES.rst
  docs/source/changes.rst
  docs/source/index.rst
Labels: documentation

#196 revise Miniconda installer script - without mamba
  docs/source/reference/_conda_base.md
Labels: bug, documentation

#205 201 conda doc md2rst
  docs/source/instrument/_install_new_instrument.rst
  docs/source/reference/_conda_base.md
  docs/source/reference/_conda_environment.md
  docs/source/reference/_create_conda_env.md
  docs/source/reference/_create_conda_env.rst
Labels: documentation

#209 use :download: role
  docs/source/instrument/_install_new_instrument.rst
Labels: documentation
