Repository BCDA-APS/bluesky_training, pull requests merged in 2023-04, with the labels that each got.

#92 update to new prjemian/synapps docker image
  .github/scripts/README.md
  .github/scripts/iocmgr.sh
  .github/scripts/start_adsim.sh
  .github/scripts/start_xxx.sh
  .github/workflows/unit-tests-pytest.yml
  install.md
  iocStarter.sh
  resources/developer/README.md
Labels: task

#96 prepare Sphinx documentation
  .github/workflows/pages.yml
  .gitignore
  docs/Makefile
  docs/make.bat
  docs/requirements.txt
  docs/source/_static/.gitkeep
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation, enhancement

#114 DOC #103 update test new inst
  docs/source/instrument/_test_new_instrument.md
  docs/source/tutor/_aps101_notes.md
  docs/source/tutor/index.rst
Labels: documentation

#121 resolve nbformat id problems
  docs/source/example/_watch_temperature.ipynb
  docs/source/howto/_basic_motor_scaler_scan.ipynb
  docs/source/howto/_count_scaler.ipynb
  docs/source/howto/_lineup_1d_peak.ipynb
  docs/source/howto/_locate_image_peak.ipynb
  docs/source/instrument/describe_instrument.ipynb
Labels: bug

#105 100 hello world
  docs/source/_static/custom.css
  docs/source/index.rst
  docs/source/reference/_FAQ.rst
  docs/source/tutor/_hello_world.ipynb
  docs/source/tutor/_start_bluesky_session.md
Labels: documentation

#126 catch-up to main
  docs/source/_static/custom.css
  docs/source/example/_watch_temperature.ipynb
  docs/source/howto/_basic_motor_scaler_scan.ipynb
  docs/source/howto/_count_scaler.ipynb
  docs/source/howto/_lineup_1d_peak.ipynb
  docs/source/howto/_locate_image_peak.ipynb
  docs/source/index.rst
  docs/source/instrument/describe_instrument.ipynb
  docs/source/reference/_FAQ.rst
  docs/source/tutor/_hello_world.ipynb
  docs/source/tutor/_start_bluesky_session.md
Labels: task

#128 Show how to use a tabbed display in the documentation.
  docs/requirements.txt
  docs/source/conf.py
  docs/source/instrument/_conda_environment.md
  docs/source/instrument/_create_conda_env.md
  docs/source/instrument/_install_new_instrument.md
  docs/source/instrument/_install_new_instrument.rst
  docs/source/instrument/instrument_template.md
Labels: documentation

#132 Catch-up with main
  bluesky/user_group_permissions.yaml
Labels: task

#135 follow upgrades in bluesky-queueserver
  .github/workflows/unit-tests-pytest.yml
  README.md
  bluesky/tests/test_bluesky_plans.py
  bluesky/user_group_permissions.yaml
  docs/source/howto/_bluesky_queueserver.md
  environment.yml
Labels: task
